services:
  postgres:
    image: postgres:18.1
    container_name: postgres_demo
    environment:
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: mysecretpwd
      POSTGRES_DB: playground_db
    volumes:
      - ~/Volumes/postgres_demo/pg_data:/var/lib/postgresql:delegated
    ports:
      - "5434:5432"
    shm_size: 1g
    command: >
      postgres
      -c synchronous_commit=off
      -c shared_buffers=512MB
      -c work_mem=64MB

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: playground@mail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpwd
    ports:
      - "8080:80"
    depends_on:
      - postgres